name: Ecoism CI Tests

on: [push]

jobs:
  lint:
    name: Eslint, prettier and solhint
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: check lint
        uses: borales/actions-yarn@v4
        with:
          cmd: format # will run `yarn format` command

  tests:
    name: Test Suite
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: install node
        uses: actions/setup-node@v3
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: install dependencies
        uses: borales/actions-yarn@v4
        with:
          cmd: install # will run `yarn install` command

      - name: build project
        uses: borales/actions-yarn@v4
        with:
          cmd: build # will run `yarn build` command

      - name: Run Test
        uses: borales/actions-yarn@v4
        with:
          cmd: test # will run `yarn build` command
